# JPG2PDF Docker Compose Configuration
services:
  jpg2pdf:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_PATH: /jpg2pdf
    container_name: jpg2pdf
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    environment:
      - BASE_PATH=/jpg2pdf
    volumes:
      - ./output:/app/output
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT:-3000}/jpg2pdf/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

